Feature/network
TW-Smart-CoE/ARK-iOS pull request #11
Opened 2022-09-07 06:07 UTC by TStrawberry

## Overview

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## In scope
- Add Network root implementation
- Add interceptor

## Check list
1. [ ] Does your submission pass tests?
2. [ ] Have you lint your code locally prior to submission?
3. [ ] Have you update the wiki of your change?

## Reference
- Card: https://trello.com/c/wlINmCUX

2022-09-07 07:41 UTC, Tony---Zhang commented on modules/Core/Sources/Network/DataSession.swift
> +    var isNetworkReachable: () -> Bool = { NetworkReachabilityManager.default?.isReachable ?? false }
可以把这些封装到不同的拦截器中吗？
比如这个可以叫“NetworkReachabilityInterceptor”

然后这些Interceptor都集成一个标准的Interceptor协议

protocol Interceptor {
fun intercept(request: Request) -> ??
}

2022-09-07 07:42 UTC, Tony---Zhang commented on modules/Core/Sources/Network/DataSession.swift
> +    public func resume(_ request: URLRequest, response: @escaping (Result<Data, Swift.Error>) -> Void) {
这个写法，我们需要修改成combine的写法，而不用写成callback这种

2022-09-07 07:44 UTC, Tony---Zhang commented on modules/Core/Sources/Network/Session.swift
> +    public func resumeWithInterceptor(_ request: Request, response: @escaping (Result<Response, Error>) -> Void) {
这个方法不要暴露出去吧？我们需要基于接口编程。我理解所有的接口都应该经过我们设定的拦截器

2022-09-07 07:50 UTC, Tony---Zhang requested changes
Need to change to combine style

func fetch(_ request: T) -> AnyPublisher<Result<Data, Swift.Error>>

2022-09-09 07:43 UTC, pujiaxin33 approved these changes

2022-09-14 04:47 UTC, Tony---Zhang approved these changes

2022-09-14 04:47 UTC, merged